gui_params = [
    {
        "name": "save_path",
        "type": "folder",
        "title": "Save path"
    },
    {
        "name": "compute_pc_features",
        "type": "bool",
        "value": True,
        "default": True,
        "title": "If True (default), pc features are computed.",
    },
    {
        "name": "compute_amplitudes",
        "type": "int",
        "value": 3,
        "default": 3,
        "title": "If True (default), waveforms amplitudes are compute.",
    },
    {
        "name": "max_channels_per_template",
        "type": "int",
        "value": 3,
        "default": 3,
        "title": "Number of principal components",
    },
    {
        "name": "n_comp",
        "type": "int",
        "value": 3,
        "default": 3,
        "title": "Number of principal components",
    },
    {
        "name": "electrode_dimensions",
        "type": "int_list",
        "value": None,
        "default": None,
        "title": "If electrode locations are 3D, it indicates the 2D dimensions to use as channel location.",
    },
    {
        "name": "grouping_property",
        "type": "str",
        "value": None,
        "default": None,
        "title": "Property to group channels. E.g. if the recording extractor has the 'group' property and 'grouping_property' is 'group', then waveforms are computed group-wise.",
    },
    {
        "name": "ms_before",
        "type": "float",
        "value": 1.0,
        "default": 1.0,
        "title": "Time period in ms to cut waveforms before the spike events.",
    },
    {
        "name": "ms_after",
        "type": "float",
        "value": 2.0,
        "default": 2.0,
        "title": "Time period in ms to cut waveforms after the spike events.",
    },
    {
        "name": "dtype",
        "type": "dtype",
        "value": None,
        "default": None,
        "title": "The dtype of underlying data (int16, float32, etc.)",
    },
    {
        "name": "amp_method",
        "type": "str",
        "value": "absolute",
        "default": "absolute",
        "title": "If 'absolute' (default), amplitudes are absolute amplitudes in uV are returned. If 'relative', amplitudes are returned as ratios between waveform amplitudes and template amplitudes.",
    },
    {
        "name": "amp_peak",
        "type": "str",
        "value": "both",
        "default": "both",
        "title": "If maximum channel has to be found among negative peaks ('neg'), positive ('pos') or both ('both' - default).",
    },
    {
        "name": "amp_frames_before",
        "type": "int",
        "value": 3,
        "default": 3,
        "title": "Frames before peak to compute amplitude.",
    },
    {
        "name": "amp_frames_after",
        "type": "int",
        "value": 3,
        "default": 3,
        "title": "Frames after peak to compute amplitude.",
    },
    {
        "name": "max_spikes_for_pca",
        "type": "int",
        "value": 100000,
        "default": 100000,
        "title": "The maximum number of waveforms used to compute PCA. If 'inf', it will use all the waveforms.",
    },
    {
        "name": "write_waveforms",
        "type": "bool",
        "value": False,
        "default": False,
        "title": "If True, waveforms are saved as waveforms.npy.",
    },
    {
        "name": "seed",
        "type": "int",
        "value": 0,
        "default": 0,
        "title": "Random seed for extracting waveforms and pcs.",
    },
]
