gui_params = [
    {
        "name": "output_folder",
        "type": "folder",
        "value": None,
        "default": None,
        "title": "Sorting output folder path.",
        "base_param": True,
    },
    {
        "name": "verbose",
        "type": "bool",
        "value": False,
        "default": False,
        "title": "If True, output from SpikeInterface element is verbose when run.",
        "base_param": True,
    },
    {
        "name": "grouping_property",
        "type": "str",
        "value": None,
        "default": None,
        "title": "Property name to be used for sorter output grouping.",
        "base_param": True,
    },
    {
        "name": "parallel",
        "type": "bool",
        "value": False,
        "default": False,
        "title": "If grouping property specifed, sort property groups in parallel if True.",
        "base_param": True,
    },
    {
        "name": "delete_output_folder",
        "type": "bool",
        "value": False,
        "default": False,
        "title": "Delete specified or default output folder on completion if True.",
        "base_param": True,
    },
    # hdsort specific parameters
    {
        "name": "detect_threshold",
        "type": "float",
        "value": 4.2,
        "default": 4.2,
        "title": "Relative detection threshold.",
    },
    {
        "name": "detect_sign",
        "type": "int",
        "value": -1,
        "default": -1,
        "title": "Use -1, or 1, depending on the sign of the spikes in the recording.",
    },
    {
        "name": "filter",
        "type": "bool",
        "value": True,
        "default": True,
        "title": "If True, the recordings are filtered.",
    },
    {
        "name": "parfor",
        "type": "bool",
        "value": True,
        "default": True,
        "title": "Use parallel processing.",
    },
    {
        "name": "hpf",
        "type": "float",
        "value": 300,
        "default": 300,
        "title": "high-pass cutoff frequency.",
    },
    {
        "name": "lpf",
        "type": "float",
        "value": 7000,
        "default": 7000,
        "title": "low-pass cutoff frequency.",
    },
    {
        "name": "max_el_per_group",
        "type": "int",
        "value": 9,
        "default": 9,
        "title": "Maximum number of electrodes per local electrode group.",
    },
    {
        "name": "min_el_per_group",
        "type": "int",
        "value": 1,
        "default": 1,
        "title": "Minimum number of electrodes per local electrode group.",
    },
    {
        "name": "add_if_nearer_than",
        "type": "float",
        "value": 20,
        "default": 20,
        "title": "Add to electrode group if distance is closer than this value.",
    },
    {
        "name": "max_distance_within_group",
        "type": "float",
        "value": 52,
        "default": 52,
        "title": "Maximum distance within group.",
    },
    {
        "name": "n_pc_dims",
        "type": "int",
        "value": 6,
        "default": 6,
        "title": "Number of pc dimensions.",
    },
    {
        "name": "chunk_size",
        "type": "int",
        "value": 50_0000,
        "default": 50_0000,
        "title": "Chunk size in number of samples.",
    },
    {
        "name": "loop_mode",
        "type": "str",
        "value": "local_parfor",
        "default": "local_parfor",
        "title": "Loop mode for sorting ('local_parfor', 'loop', 'grid').",
    },
]
