gui_params = [
    {
        "name": "output_folder",
        "type": "folder",
        "value": None,
        "default": None,
        "title": "Sorting output folder path.",
        "base_param": True,
    },
    {
        "name": "verbose",
        "type": "bool",
        "value": False,
        "default": False,
        "title": "If True, output from SpikeInterface element is verbose when run.",
        "base_param": True,
    },
    {
        "name": "grouping_property",
        "type": "str",
        "value": None,
        "default": None,
        "title": "Property name to be used for sorter output grouping.",
        "base_param": True,
    },
    {
        "name": "parallel",
        "type": "bool",
        "value": False,
        "default": False,
        "title": "If grouping property specifed, sort property groups in parallel if True.",
        "base_param": True,
    },
    {
        "name": "delete_output_folder",
        "type": "bool",
        "value": False,
        "default": False,
        "title": "Delete specified or default output folder on completion if True.",
        "base_param": True,
    },
    # herdingspikes specific parameters
    # core params
    {
        "name": "clustering_bandwidth",
        "type": "float",
        "value": 5.5,
        "default": 5.5,
        "title": "Meanshift bandwidth.",
    },
    {
        "name": "clustering_alpha",
        "type": "float",
        "value": 5.5,
        "default": 5.5,
        "title": "Scalar for the PC components when clustering.",
    },
    {
        "name": "clustering_n_jobs",
        "type": "int",
        "value": -1,
        "default": -1,
        "title": "Number of cores. Default uses all cores.",
    },
    {
        "name": "clustering_bin_seeding",
        "type": "bool",
        "value": True,
        "default": True,
        "title": "Clustering bin seeding.",
    },
    {
        "name": "clustering_min_bin_freq",
        "type": "int",
        "value": 16,
        "default": 16,
        "title": "Minimum spikes per bin for bin seeding.",
    },
    {
        "name": "clustering_subset",
        "type": "int",
        "value": None,
        "default": None,
        "title": "Number of spikes used to build clusters. All by default.",
    },
    {
        "name": "left_cutout_time",
        "type": "float",
        "value": 0.3,
        "default": 0.3,
        "title": "Cutout size before peak (ms).",
    },
    {
        "name": "right_cutout_time",
        "type": "float",
        "value": 1.8,
        "default": 1.8,
        "title": "Cutout size after peak (ms).",
    },
    {
        "name": "detection_threshold",
        "type": "int",
        "value": 20,
        "default": 20,
        "title": "Detection threshold",
    },
    # extra probe params
    {
        "name": "probe_masked_channels",
        "type": "list",
        "value": [],
        "default": [],
        "title": "Masked channels",
    },
    {
        "name": "probe_inner_radius",
        "type": "float",
        "value": 70,
        "default": 70,
        "title": "Defines area around probe channel for localization",
    },
    {
        "name": "probe_neighbor_radius",
        "type": "float",
        "value": 90,
        "default": 90,
        "title": "Defines area around probe channel for neighbor classification.",
    },
    {
        "name": "probe_event_length",
        "type": "float",
        "value": 0.26,
        "default": 0.26,
        "title": "Probe event length (seconds).",
    },
    {
        "name": "probe_peak_jitter",
        "type": "float",
        "value": 0.2,
        "default": 0.2,
        "title": "Maxmimum peak misalignment (seconds).",
    },
    # extra detection params
    {
        "name": "num_com_centers",
        "type": "int",
        "value": 1,
        "default": 1,
        "title": "Number of centroids to average when localizing.",
    },
    {
        "name": "maa",
        "type": "int",
        "value": 12,
        "default": 12,
        "title": "maa."
    },
    {
        "name": "ahpthr",
        "type": "int",
        "value": 11,
        "default": 11,
        "title": "ahpthr.",
    },
    {
        "name": "out_file_name",
        "type": "str",
        "value": "HS2_detected",
        "default": "HS2_detected",
        "title": "File name for storage of unclustered detected spikes.",
    },
    {
        "name": "decay_filtering",
        "type": "bool",
        "value": False,
        "default": False,
        "title": "Experimental: Set to True at your risk. ;^)"
    },
    {
        "name": "save_all",
        "type": "bool",
        "value": False,
        "default": False,
        "title": "Save all working files after sorting."
    },
    {
        "name": "amp_evaluation_time",
        "type": "float",
        "value": 0.4,
        "default": 0.4,
        "title": "Amplitude evaluation time (seconds).",
    },
    {
        "name": "spk_evaluation_time",
        "type": "float",
        "value": 1.0,
        "default": 1.0,
        "title": "Spike evaluation time (seconds).",
    },
    # extra pca params
    {
        "name": "pca_ncomponents",
        "type": "int",
        "value": 2,
        "default": 2,
        "title": "Number of principal components to use when clustering.",
    },
    {
        "name": "pca_whiten",
        "type": "bool",
        "value": True,
        "default": True,
        "title": "if true, whiten data after pca.",
    },
    # bandpass filter
    {
        "name": "freq_min",
        "type": "float",
        "value": 300.0,
        "default": 300.0,
        "title": "Low-pass frequency",
    },
    {
        "name": "freq_max",
        "type": "float",
        "value": 6000.0,
        "default": 6000.0,
        "title": "High-pass frequency",
    },
    {
        "name": "filter",
        "type": "bool",
        "value": True,
        "default": True,
        "title": "Bandpass filters the recording if True",
    },
    # rescale traces
    {
        "name": "pre_scale",
        "type": "bool",
        "value": True,
        "default": True,
        "title": "Scales recording traces to optimize HerdingSpikes performance",
    },
    {
        "name": "pre_scale_value",
        "type": "float",
        "value": 20.0,
        "default": 20.0,
        "title": "Scale to apply in case of pre-scaling of traces",
    },
    # other
    {
        "name": "filter_duplicates",
        "type": "bool",
        "value": True,
        "default": True,
        "title": "Rremove duplicates (based on spk_evaluation_time).",
    },
]
