gui_params = [
    {
        "name": "output_folder",
        "type": "folder",
        "value": None,
        "default": None,
        "title": "Sorting output folder path.",
        "base_param": True,
    },
    {
        "name": "verbose",
        "type": "bool",
        "value": False,
        "default": False,
        "title": "If True, output from SpikeInterface element is verbose when run.",
        "base_param": True,
    },
    {
        "name": "grouping_property",
        "type": "str",
        "value": None,
        "default": None,
        "title": "Property name to be used for sorter output grouping.",
        "base_param": True,
    },
    {
        "name": "parallel",
        "type": "bool",
        "value": False,
        "default": False,
        "title": "If grouping property specifed, sort property groups in parallel if True.",
        "base_param": True,
    },
    {
        "name": "delete_output_folder",
        "type": "bool",
        "value": False,
        "default": False,
        "title": "Delete specified or default output folder on completion if True.",
        "base_param": True,
    },
    # Tridesclous specific parameters
    {
        "name": "highpass_freq",
        "type": "float",
        "value": 400.0,
        "default": 400.0,
        "title": "High-pass frequency",
    },
    {
        "name": "lowpass_freq",
        "type": "float",
        "value": 5000.0,
        "default": 5000.0,
        "title": "Low-pass frequency",
    },
    {
        "name": "peak_sign",
        "type": "str",
        "value": "-",
        "default": "-",
        "title": "Negative or positive peak sign",
    },
    {
        "name": "relative_threshold",
        "type": "float",
        "value": 5.0,
        "default": 5.0,
        "title": "Relative threshold for detection",
    },
    {
        "name": "peak_span_ms",
        "type": "float",
        "value": 0.7,
        "default": 0.7,
        "title": "Time span of peaks for detected events (ms)",
    },
    {
        "name": "wf_left_ms",
        "type": "float",
        "value": -2.0,
        "default": -2.0,
        "title": "Waveform length before peak (ms)",
    },
    {
        "name": "wf_right_ms",
        "type": "float",
        "value": 3.0,
        "default": 3.0,
        "title": "Waveform length after peak (ms)",
    },
    {
        "name": "feature_method",
        "type": "str",
        "value": "auto",
        "default": "auto",
        "title": "Feature Extraction Method",
    },
    {
        "name": "cluster_method",
        "type": "str",
        "value": "auto",
        "default": "auto",
        "title": "Clustering Method",
    },
    {
        "name": "clean_catalogue_gui",
        "type": "bool",
        "value": False,
        "default": False,
        "title": "Clean catalogue with an interactive window",
    },
]
